In [1]:
import numpy as np

In [2]:
def numerical_derivative(f, x):
    delta_x = 1e-4 # 0.0001
    grad = np.zeros_like(x)
    
    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
    
    while not it.finished:
        idx = it.multi_index        
        tmp_val = x[idx]
        x[idx] = float(tmp_val) + delta_x
        fx1 = f(x) # f(x+delta_x)
        
        x[idx] = tmp_val - delta_x 
        fx2 = f(x) # f(x-delta_x)
        grad[idx] = (fx1 - fx2) / (2*delta_x)
        
        x[idx] = tmp_val 
        it.iternext()   
        
    return grad

def sigmoid(z):
    return 1 / (1+np.exp(-z))

In [3]:
class ClassificationCrossEntropy:
    def __init__(self, xdata, tdata, learning_rate, iteration_count):
        self.xdata = xdata
        self.tdata = tdata
        
        self.learning_rate = learning_rate
        self.iteration_count = iteration_count
        
        self.W = np.random.rand(self.xdata.shape[1], 1)
        self.b = np.random.rand(1)
        
        print("ClassificationCrossEntropy Object is created")
        
        
    def getW_b(self):
        return self.W, self.b
    
    def loss_func(self):
        delta = 1e-7
        z = np.dot(self.xdata, self.W) + self.b
        y = sigmoid(z)
    
        return (-1) * (np.sum(self.tdata*np.log(y+delta) + (1 - self.tdata)*np.log(1 - y + delta)))

    def loss_val(self):
        delta = 1e-7
        z = np.dot(self.xdata, self.W) + self.b
        y = sigmoid(z)
    
        return (-1) * (np.sum(self.tdata*np.log(y+delta) + (1 - self.tdata)*np.log(1 - y + delta)))
    
    def predict(self, test_data):
        z = np.dot(test_data, self.W) + self.b
        y = sigmoid(z)
        
        if y >= 0.5:
            result = 1
        elif y < 0.5:
            result = 0
    
        return y, result
    
    def train(self):
        f = lambda x : self.loss_func()

        print("Initial loss value = ", self.loss_val(), "Initial W = ", self.W, "\n", ", b = ", self.b )

        for step in range(self.iteration_count):
            self.W -= self.learning_rate * numerical_derivative(f, self.W)
            self.b -= self.learning_rate * numerical_derivative(f, self.b)
    
            if (step % 10000 == 0):
                print("step = ", step, "loss value = ", self.loss_val(), "W = ", self.W, ", b = ", self.b )

In [4]:
x_data = np.array([[2, 4], [4, 11], [6, 6], [8, 5], [10, 7], [12, 16], [14, 8], [16, 3],  [18, 7]])
t_data = np.array([0, 0, 0, 0, 1, 1, 1, 1, 1]).reshape(9, 1)

print("x_data.shape = ", x_data.shape, ", t_data.shape = ", t_data.shape)

x_data.shape =  (9, 2) , t_data.shape =  (9, 1)


In [5]:
obj1 = ClassificationCrossEntropy(x_data, t_data, 1e-2, 100001)

obj1.train()

ClassificationCrossEntropy Object is created
Initial loss value =  10.071867079495341 Initial W =  [[0.40073901]
 [0.0095857 ]] 
 , b =  [0.32631788]
step =  0 loss value =  4.677987168387937 W =  [[ 0.2181914 ]
 [-0.22144509]] , b =  [0.31830346]
step =  10000 loss value =  0.40411300077811535 W =  [[1.2808907 ]
 [0.31295417]] , b =  [-13.32985414]
step =  20000 loss value =  0.24728674344125304 W =  [[1.56567596]
 [0.53756454]] , b =  [-17.23882761]
step =  30000 loss value =  0.17769225633852367 W =  [[1.75841341]
 [0.68517737]] , b =  [-19.85643342]
step =  40000 loss value =  0.13841662780641623 W =  [[1.90508768]
 [0.79376952]] , b =  [-21.82617024]
step =  50000 loss value =  0.11325321028362499 W =  [[2.02337486]
 [0.8795357 ]] , b =  [-23.4040131]
step =  60000 loss value =  0.09578031748460536 W =  [[2.12241524]
 [0.95036432]] , b =  [-24.71935223]
step =  70000 loss value =  0.08295126955608935 W =  [[2.20756019]
 [1.01066569]] , b =  [-25.84669424]
step =  80000 loss value 

In [13]:
obj1.predict(np.array([3, 17]).reshape(1, 2))

(array([[0.15443934]]), 0)

In [7]:
obj1.predict([5, 8])

(array([0.00071349]), 0)

In [8]:
obj1.predict([7, 21])

(array([0.99999642]), 1)

In [9]:
obj1.predict([12, 0])

(array([0.59983718]), 1)