In [1]:
import numpy as np

# 예제 2) MSE 사용

##### 미분 값 계산

In [2]:
def numerical_derivative(f, x):
    delta_x = 1e-4 # 0.0001
    grad = np.zeros_like(x)
    
    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
    
    while not it.finished:
        idx = it.multi_index        
        tmp_val = x[idx]
        x[idx] = float(tmp_val) + delta_x
        fx1 = f(x) # f(x+delta_x)
        
        x[idx] = tmp_val - delta_x 
        fx2 = f(x) # f(x-delta_x)
        grad[idx] = (fx1 - fx2) / (2*delta_x)
        
        x[idx] = tmp_val 
        it.iternext()   
        
    return grad

##### x값, y값 대입

In [3]:
x_data = np.array([2, 4, 6, 8, 10, 12, 14, 16, 18, 20]).reshape(10, 1)
t_data = np.array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1]).reshape(10, 1)

print("x_data.shape = ", x_data.shape, ", t_data.shape = ", t_data.shape)

x_data.shape =  (10, 1) , t_data.shape =  (10, 1)


##### W, b에 랜덤 값 대입

In [4]:
W = np.random.rand(1, 1)
b = np.random.rand(1)

print("W = ", W, ", W.shape = ", W.shape, ", b = ", b, ", b.shape = ", b.shape)

W =  [[0.37148038]] , W.shape =  (1, 1) , b =  [0.31090593] , b.shape =  (1,)


##### 손실 함수 정의, 손실 함수 값 계산, 미래 값 예측

In [5]:
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

def loss_func(x, t):
    z = np.dot(x, W) + b
    y = sigmoid(z)
    
    return (np.sum((t-y)**2)) / (len(x))

def loss_val(x, t):
    z = np.dot(x, W) + b
    y = sigmoid(z)
    
    return (np.sum((t-y)**2)) / (len(x))

def predict(x):
    z = np.dot(x, W) + b
    y = sigmoid(z)
    
    if y > 0.5:
        result = 1
    elif y < 0.5:
        result = 0
    
    return y, result

##### learning 과정

In [6]:
learning_rate = 2.9e-2

f = lambda x : loss_func(x_data, t_data)

print("Initial loss value = ", loss_val(x_data, t_data), "Initial W = ", W, "\n", ", b = ", b )

for step in range(100001):
    W -= learning_rate * numerical_derivative(f, W)
    b -= learning_rate * numerical_derivative(f, b)
    
    if (step % 10000 == 0):
        print("step = ", step, "loss value = ", loss_val(x_data, t_data), "W = ", W, ", b = ",b )

Initial loss value =  0.5022174267823611 Initial W =  [[0.37148038]] 
 , b =  [0.31090593]
step =  0 loss value =  0.49895090063756814 W =  [[0.36210257]] , b =  [0.30870864]
step =  10000 loss value =  0.04172033980307836 W =  [[0.44794891]] , b =  [-5.68783457]
step =  20000 loss value =  0.03116008642378368 W =  [[0.57881751]] , b =  [-7.41730515]
step =  30000 loss value =  0.026106923663988108 W =  [[0.67042182]] , b =  [-8.62144773]
step =  40000 loss value =  0.022886001994546903 W =  [[0.74385797]] , b =  [-9.58425365]
step =  50000 loss value =  0.020557729543019078 W =  [[0.80642788]] , b =  [-10.4032933]
step =  60000 loss value =  0.018751363584566475 W =  [[0.86161404]] , b =  [-11.12489878]
step =  70000 loss value =  0.017285481791447326 W =  [[0.91137346]] , b =  [-11.77503218]
step =  80000 loss value =  0.016058689032991447 W =  [[0.95692505]] , b =  [-12.36983047]
step =  90000 loss value =  0.015008885629233184 W =  [[0.99908454]] , b =  [-12.92007551]
step =  10000

In [7]:
predict([13.0])

(array([0.5165421]), 1)

In [8]:
predict([11.0])

(array([0.11808788]), 0)

In [9]:
predict([31.0])

(array([0.99999999]), 1)

In [10]:
predict([3.0])

(array([3.3029161e-05]), 0)

In [11]:
predict([3.5])

(array([5.55110619e-05]), 0)