In [1]:
import numpy as np

# 예제 1) Cross-Entropy 사용

##### 미분 값 계산

In [14]:
def numerical_derivative(f, x):
    delta_x = 1e-4 # 0.0001
    grad = np.zeros_like(x)
    
    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
    
    while not it.finished:
        idx = it.multi_index        
        tmp_val = x[idx]
        x[idx] = float(tmp_val) + delta_x
        fx1 = f(x) # f(x+delta_x)
        
        x[idx] = tmp_val - delta_x 
        fx2 = f(x) # f(x-delta_x)
        grad[idx] = (fx1 - fx2) / (2*delta_x)
        
        x[idx] = tmp_val 
        it.iternext()   
        
    return grad

##### x값, y값 대입

In [15]:
x_data = np.array([2, 4, 6, 8, 10, 12, 14, 16, 18, 20]).reshape(10, 1)
t_data = np.array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1]).reshape(10, 1)

print("x_data.shape = ", x_data.shape, ", t_data.shape = ", t_data.shape)

x_data.shape =  (10, 1) , t_data.shape =  (10, 1)


##### W, b에 랜덤 값 대입

In [16]:
W = np.random.rand(1, 1)
b = np.random.rand(1)

print("W = ", W, ", W.shape = ", W.shape, ", b = ", b, ", b.shape = ", b.shape)

W =  [[0.40739088]] , W.shape =  (1, 1) , b =  [0.7968633] , b.shape =  (1,)


##### 손실 함수 정의, 손실 함수 값 계산, 미래 값 예측

In [5]:
def loss_func(x, t):
    y = 1/(1 + np.exp(np.dot(x, W) + b))
    
    return (-1) * (np.sum(t*np.log(y) + (1 - t)*np.log(1 - y)))

def loss_val(x, t):
    y = 1/(1 + np.exp(np.dot(x, W) + b))
    
    return (-1) * (np.sum(t*np.log(y) + (1 - t)*np.log(1 - y)))

def predict(x):
    y = 1/(1 + np.exp(np.dot(x, W) + b))
    if y > 0.5:
        result = 1
    elif y < 0.5:
        result = 0
    
    return y, result

##### learning 과정

In [17]:
learning_rate = 2.9e-2

f = lambda x : loss_func(x_data, t_data)

print("Initial loss value = ", loss_val(x_data, t_data), "Initial W = ", W, "\n", ", b = ", b )

for step in range(100001):
    W -= learning_rate * numerical_derivative(f, W)
    b -= learning_rate * numerical_derivative(f, b)
    
    if (step % 10000 == 0):
        print("step = ", step, "loss value = ", loss_val(x_data, t_data), "W = ", W, ", b = ",b )

Initial loss value =  31.225811804202888 Initial W =  [[0.40739088]] 
 , b =  [0.7968633]
step =  0 loss value =  58.59594131000075 W =  [[-1.53051269]] , b =  [0.96798599]
step =  10000 loss value =  0.30264637830295593 W =  [[-1.8447739]] , b =  [23.88847641]
step =  20000 loss value =  0.20213145132038013 W =  [[-2.256597]] , b =  [29.24914163]
step =  30000 loss value =  0.15204330303520083 W =  [[-2.54834579]] , b =  [33.04482045]
step =  40000 loss value =  0.121781747287407 W =  [[-2.77537332]] , b =  [35.99779796]
step =  50000 loss value =  0.10149574496789565 W =  [[-2.96134365]] , b =  [38.41643412]
step =  60000 loss value =  0.08695393874840995 W =  [[-3.11883657]] , b =  [40.46454421]
step =  70000 loss value =  0.0760243297092074 W =  [[-3.25539294]] , b =  [42.24028857]
step =  80000 loss value =  0.06751367474578422 W =  [[-3.37590319]] , b =  [43.80731073]
step =  90000 loss value =  0.060701665920296 W =  [[-3.48372314]] , b =  [45.20927548]
step =  100000 loss value

In [18]:
predict([13.0])

(array([0.51970958]), 1)

In [19]:
predict([11.0])

(array([0.00083802]), 0)

In [20]:
predict([31.0])

(array([1.]), 1)

In [21]:
predict([3.0])

(array([3.02731635e-16]), 0)

In [22]:
predict([3.5])

(array([1.81433616e-15]), 0)