In [1]:
import numpy as np

In [2]:
def numerical_derivative(f, x):
    delta_x = 1e-4 # 0.0001
    grad = np.zeros_like(x)
    
    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
    
    while not it.finished:
        idx = it.multi_index        
        tmp_val = x[idx]
        x[idx] = float(tmp_val) + delta_x
        fx1 = f(x) # f(x+delta_x)
        
        x[idx] = tmp_val - delta_x 
        fx2 = f(x) # f(x-delta_x)
        grad[idx] = (fx1 - fx2) / (2*delta_x)
        
        x[idx] = tmp_val 
        it.iternext()   
        
    return grad

def sigmoid(z):
    return 1 / (1+np.exp(-z))

In [3]:
class ClassificationCrossEntropy:
    def __init__(self, xdata, tdata, learning_rate, iteration_count):
        self.xdata = xdata
        self.tdata = tdata
        
        self.learning_rate = learning_rate
        self.iteration_count = iteration_count
        
        self.W = np.random.rand(self.xdata.shape[1], 1)
        self.b = np.random.rand(1)
        
        print("ClassificationCrossEntropy Object is created")
        
        
    def getW_b(self):
        return self.W, self.b
    
    def loss_func(self):
        delta = 1e-7
        z = np.dot(self.xdata, self.W) + self.b
        y = sigmoid(z)
    
        return (-1) * (np.sum(self.tdata*np.log(y+delta) + (1 - self.tdata)*np.log(1 - y + delta)))

    def loss_val(self):
        delta = 1e-7
        z = np.dot(self.xdata, self.W) + self.b
        y = sigmoid(z)
    
        return (-1) * (np.sum(self.tdata*np.log(y+delta) + (1 - self.tdata)*np.log(1 - y + delta)))
    
    def predict(self, test_data):
        z = np.dot(test_data, self.W) + self.b
        y = sigmoid(z)
        
        if y >= 0.5:
            result = 1
        elif y < 0.5:
            result = 0
    
        return y, result
    
    def train(self):
        f = lambda x : self.loss_func()

        print("Initial loss value = ", self.loss_val(), "Initial W = ", self.W, "\n", ", b = ", self.b )

        for step in range(self.iteration_count):
            self.W -= self.learning_rate * numerical_derivative(f, self.W)
            self.b -= self.learning_rate * numerical_derivative(f, self.b)
    
            if (step % 10000 == 0):
                print("step = ", step, "loss value = ", self.loss_val(), "W = ", self.W, ", b = ", self.b )

In [4]:
x_data = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
t_data = np.array([0, 1, 1, 0]).reshape(4, 1)

print("x_data.shape = ", x_data.shape, ", t_data.shape = ", t_data.shape)

x_data.shape =  (4, 2) , t_data.shape =  (4, 1)


In [5]:
obj1 = ClassificationCrossEntropy(x_data, t_data, 1e-2, 100001)

obj1.train()

ClassificationCrossEntropy Object is created
Initial loss value =  3.3944329010677983 Initial W =  [[0.78159785]
 [0.68718863]] 
 , b =  [0.30567311]
step =  0 loss value =  3.3792437139767233 W =  [[0.77556907]
 [0.68134199]] , b =  [0.29662723]
step =  10000 loss value =  2.772587922239862 W =  [[4.72864584e-08]
 [4.72850196e-08]] , b =  [-5.60356292e-08]
step =  20000 loss value =  2.7725879222398615 W =  [[1.65815139e-11]
 [1.40768508e-11]] , b =  [-1.61068936e-11]
step =  30000 loss value =  2.7725879222398615 W =  [[1.65815139e-11]
 [1.40768508e-11]] , b =  [-1.61068936e-11]
step =  40000 loss value =  2.7725879222398615 W =  [[1.65815139e-11]
 [1.40768508e-11]] , b =  [-1.61068936e-11]
step =  50000 loss value =  2.7725879222398615 W =  [[1.65815139e-11]
 [1.40768508e-11]] , b =  [-1.61068936e-11]
step =  60000 loss value =  2.7725879222398615 W =  [[1.65815139e-11]
 [1.40768508e-11]] , b =  [-1.61068936e-11]
step =  70000 loss value =  2.7725879222398615 W =  [[1.65815139e-11]


0, 1, 1, 0 이 나와야 하는데 다른 값이 나온다,,? -> XOR 문제

In [6]:
obj1.predict(np.array([0, 0]).reshape(1, 2))

(array([[0.5]]), 0)

In [7]:
obj1.predict([0, 1])

(array([0.5]), 0)

In [8]:
obj1.predict([1, 0])

(array([0.5]), 1)

In [9]:
obj1.predict([1, 1])

(array([0.5]), 1)