In [1]:
import numpy as np

In [2]:
class ClassificationCrossEntropy:
    def __init__(self, xdata, tdata, learning_rate, iteration_count):
        self.xdata = xdata
        self.tdata = tdata
        
        self.learning_rate = learning_rate
        self.iteration_count = iteration_count
        
        self.W = np.random.rand(self.xdata.shape[1], 1)
        self.b = np.random.rand(1)
        
        print("ClassificationCrossEntropy Object is created")
        
        
    def getW_b(self):
        return self.W, self.b
    
    def loss_func(self):
        delta = 1e-7
        z = np.dot(self.xdata, self.W) + self.b
        y = sigmoid(z)
    
        return (-1) * (np.sum(self.tdata*np.log(y+delta) + (1 - self.tdata)*np.log(1 - y + delta)))

    def loss_val(self):
        delta = 1e-7
        z = np.dot(self.xdata, self.W) + self.b
        y = sigmoid(z)
    
        return (-1) * (np.sum(self.tdata*np.log(y+delta) + (1 - self.tdata)*np.log(1 - y + delta)))
    
    def predict(self, test_data):
        z = np.dot(test_data, self.W) + self.b
        y = sigmoid(z)
        
        if y >= 0.5:
            result = 1
        elif y < 0.5:
            result = 0
    
        return y, result
    
    def train(self):
        f = lambda x : self.loss_func()

        print("Initial loss value = ", self.loss_val(), "Initial W = ", self.W, "\n", ", b = ", self.b )

        for step in range(self.iteration_count):
            self.W -= self.learning_rate * numerical_derivative(f, self.W)
            self.b -= self.learning_rate * numerical_derivative(f, self.b)
    
            if (step % 10000 == 0):
                print("step = ", step, "loss value = ", self.loss_val(), "W = ", self.W, ", b = ", self.b )

In [3]:
def numerical_derivative(f, x):
    delta_x = 1e-4 # 0.0001
    grad = np.zeros_like(x)
    
    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
    
    while not it.finished:
        idx = it.multi_index        
        tmp_val = x[idx]
        x[idx] = float(tmp_val) + delta_x
        fx1 = f(x) # f(x+delta_x)
        
        x[idx] = tmp_val - delta_x 
        fx2 = f(x) # f(x-delta_x)
        grad[idx] = (fx1 - fx2) / (2*delta_x)
        
        x[idx] = tmp_val 
        it.iternext()   
        
    return grad

def sigmoid(z):
    return 1 / (1+np.exp(-z))

In [4]:
x_data = np.array([2, 4, 6, 8, 10, 12, 14, 16, 18, 20]).reshape(10, 1)
t_data = np.array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1]).reshape(10, 1)

print("x_data.shape = ", x_data.shape, ", t_data.shape = ", t_data.shape)

x_data.shape =  (10, 1) , t_data.shape =  (10, 1)


In [5]:
obj1 = ClassificationCrossEntropy(x_data, t_data, 2.9e-2, 100001)

obj1.train()

ClassificationCrossEntropy Object is created
Initial loss value =  14.17083150569005 Initial W =  [[0.28943256]] 
 , b =  [0.18013887]
step =  0 loss value =  53.55500959913554 W =  [[-0.81097237]] , b =  [0.26934697]
step =  10000 loss value =  0.30271059650345944 W =  [[1.84455568]] , b =  [-23.88563452]
step =  20000 loss value =  0.20215884134528914 W =  [[2.25645301]] , b =  [-29.24726803]
step =  30000 loss value =  0.15205837285219126 W =  [[2.54823746]] , b =  [-33.04341128]
step =  40000 loss value =  0.12179109832831263 W =  [[2.77528637]] , b =  [-35.99666712]
step =  50000 loss value =  0.10150196485841761 W =  [[2.96127103]] , b =  [-38.41548969]
step =  60000 loss value =  0.08695825761114546 W =  [[3.11877423]] , b =  [-40.46373355]
step =  70000 loss value =  0.07602740832668546 W =  [[3.25533834]] , b =  [-42.23957862]
step =  80000 loss value =  0.06751589988927 W =  [[3.37585463]] , b =  [-43.80667934]
step =  90000 loss value =  0.060703278988637054 W =  [[3.4836794

In [11]:
obj1.predict([13.0])

(array([0.5197096]), 1)

In [12]:
obj1.predict([11.0])

(array([0.00083808]), 0)

In [13]:
obj1.predict([31.0])

(array([1.]), 1)

In [14]:
obj1.predict([3.0])

(array([3.02852014e-16]), 0)

In [15]:
obj1.predict([3.5])

(array([1.81502155e-15]), 0)