In [1]:
import numpy as np

In [2]:
X = np.array([ [7, 5, 3, 1], [1, 2, 3, 4], [4, 0, 2, 8] ])

X.shape

(3, 4)

In [3]:
A = X.reshape(-1, 3)

A

array([[7, 5, 3],
       [1, 1, 2],
       [3, 4, 4],
       [0, 2, 8]])

In [4]:
B = A[0:2, 1:2]

B

array([[5],
       [1]])

In [5]:
C = A[1:, :-1]

C

array([[1, 1],
       [3, 4],
       [0, 2]])

In [6]:
D = np.argmax(A, 1)

D

array([0, 2, 1, 2], dtype=int64)

In [7]:
E = C.reshape(-1,6)

E

array([[1, 1, 3, 4, 0, 2]])

In [8]:
F = np.sum(E)

F

11